# Generated by Django 5.0.7 on 2024-08-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcms', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrist', 'Pediatrist'), ('Physician', 'Physician'), ('Surgeon', 'Surgeon'), ('Neurologist', 'Neurologist'), ('Gynecologist', 'Gynecologist'), ('Ostetrician', 'Ostetrician'), ('Radiologist', 'Radiologist'), ('Dentist', 'Dentist'), ('General pratictioner', 'General pratictioner')], max_length=50),
        ),
    ]
